/**
 * Eventos do módulo Equipamento.
 *
 * Na branch `main` este arquivo NÃO é importado — a plataforma de notificações
 * funciona apenas com eventos genéricos (`platform-events.ts`).
 *
 * Na branch `controle-equipamento`, registre em `index.ts`:
 *   import { EQUIPAMENTO_NOTIFICATION_EVENTS } from './modules/equipamento-events';
 *   registerNotificationEvents(EQUIPAMENTO_NOTIFICATION_EVENTS);
 */
import { defineNotificationEvent } from '@/lib/notification-events/define-event';
import type { NotificationEventDefinition } from '@/types/notification-events';

export const EQUIPAMENTO_NOTIFICATION_EVENTS: NotificationEventDefinition[] = [
  defineNotificationEvent({
    slug: 'loan.due_soon',
    module: 'equipamento',
    category: 'loans',
    label: 'Próximo do vencimento',
    description: 'Aviso quando um empréstimo estiver próximo da data limite.',
    example: 'MARTELETE SDS PLUS — vence em 3 dias · João Silva · Residencial Horizonte',
    severity: 'warning',
    default_audience: ['field_operator', 'manager'],
    default_channels: ['app', 'whatsapp'],
    supports_escalation: true,
  }),
  defineNotificationEvent({
    slug: 'loan.overdue',
    module: 'equipamento',
    category: 'loans',
    label: 'Empréstimo vencido',
    description: 'Alerta quando um equipamento ultrapassar o prazo máximo permitido.',
    example: 'GERADOR 10 KVA — vencido há 7 dias · Maria Santos',
    severity: 'critical',
    default_audience: ['manager', 'field_operator'],
    default_channels: ['app', 'email', 'whatsapp'],
    supports_escalation: true,
  }),
  defineNotificationEvent({
    slug: 'loan.renewed',
    module: 'equipamento',
    category: 'loans',
    label: 'Renovação realizada',
    description: 'Aviso sempre que um empréstimo for renovado.',
    example: 'BETONEIRA 320L — renovação registrada · Carlos Oliveira',
    severity: 'info',
    default_audience: ['manager'],
    default_channels: ['app'],
  }),
  defineNotificationEvent({
    slug: 'loan.renewal_limit_exceeded',
    module: 'equipamento',
    category: 'loans',
    label: 'Excesso de renovações',
    description: 'Alerta quando um equipamento ultrapassar a quantidade recomendada de renovações.',
    example: 'MARTELETE SDS PLUS — 5 renovações · avaliar devolução ou substituição',
    severity: 'warning',
    default_audience: ['manager'],
    default_channels: ['app', 'email'],
  }),
  defineNotificationEvent({
    slug: 'loan.created',
    module: 'equipamento',
    category: 'loans',
    label: 'Novo empréstimo',
    description: 'Aviso sempre que um equipamento for emprestado.',
    example: 'GERADOR 10 KVA emprestado · João Silva',
    severity: 'info',
    default_audience: ['field_operator', 'manager'],
    default_channels: ['app'],
  }),
  defineNotificationEvent({
    slug: 'loan.returned',
    module: 'equipamento',
    category: 'loans',
    label: 'Devolução registrada',
    description: 'Confirmação de devolução de equipamento.',
    severity: 'info',
    default_audience: ['field_operator', 'manager'],
    default_channels: ['app'],
  }),
  defineNotificationEvent({
    slug: 'equipment.idle',
    module: 'equipamento',
    category: 'inventory',
    label: 'Equipamento parado',
    description: 'Alerta quando um equipamento permanecer sem utilização por determinado período.',
    example: 'BOMBA MANGOTE 3" — sem uso há 45 dias · custo R$ 2.680/mês',
    severity: 'warning',
    default_audience: ['manager', 'finance'],
    default_channels: ['app', 'email'],
  }),
  defineNotificationEvent({
    slug: 'equipment.unused_since_registration',
    module: 'equipamento',
    category: 'inventory',
    label: 'Cadastrado sem utilização',
    description: 'Equipamento recém-cadastrado sem nenhuma movimentação registrada.',
    example: 'Equipamento cadastrado há 20 dias sem movimentação',
    severity: 'warning',
    default_audience: ['manager'],
    default_channels: ['app'],
  }),
  defineNotificationEvent({
    slug: 'equipment.below_minimum_stock',
    module: 'equipamento',
    category: 'inventory',
    label: 'Estoque abaixo do mínimo',
    description: 'Quando a quantidade disponível ficar abaixo do mínimo configurado.',
    example: 'MARTELETE SDS PLUS — 2 disponíveis · mínimo 5',
    severity: 'warning',
    default_audience: ['manager', 'admin'],
    default_channels: ['app', 'email'],
  }),
  defineNotificationEvent({
    slug: 'maintenance.sent',
    module: 'equipamento',
    category: 'maintenance',
    label: 'Enviado para manutenção',
    description: 'Quando um equipamento for encaminhado para manutenção.',
    example: 'SERRA CIRCULAR 7¼ enviada para manutenção',
    severity: 'info',
    default_audience: ['field_operator', 'manager'],
    default_channels: ['app'],
  }),
  defineNotificationEvent({
    slug: 'maintenance.completed',
    module: 'equipamento',
    category: 'maintenance',
    label: 'Manutenção concluída',
    description: 'Equipamento liberado e pronto para utilização.',
    severity: 'info',
    default_audience: ['field_operator', 'manager'],
    default_channels: ['app'],
  }),
  defineNotificationEvent({
    slug: 'maintenance.overdue',
    module: 'equipamento',
    category: 'maintenance',
    label: 'Manutenção atrasada',
    description: 'Equipamento em manutenção além do prazo previsto.',
    example: 'Em manutenção há 20 dias · prazo previsto 5 dias',
    severity: 'critical',
    default_audience: ['manager'],
    default_channels: ['app', 'email', 'whatsapp'],
    supports_escalation: true,
  }),
  defineNotificationEvent({
    slug: 'maintenance.frequency_high',
    module: 'equipamento',
    category: 'maintenance',
    label: 'Excesso de manutenções',
    description: 'Equipamento com frequência elevada de manutenções no período.',
    example: 'ESMERILHADEIRA 2200W — 8 manutenções nos últimos 12 meses',
    severity: 'warning',
    default_audience: ['manager', 'finance'],
    default_channels: ['app', 'email'],
  }),
  defineNotificationEvent({
    slug: 'maintenance.cost_high',
    module: 'equipamento',
    category: 'maintenance',
    label: 'Custo elevado de manutenção',
    description: 'Equipamento acumulou custo elevado de manutenção no período.',
    example: 'R$ 4.500 em manutenção este ano',
    severity: 'warning',
    default_audience: ['finance', 'manager'],
    default_channels: ['app', 'email'],
  }),
  defineNotificationEvent({
    slug: 'critical.idle',
    module: 'equipamento',
    category: 'critical',
    label: 'Crítico parado',
    description: 'Equipamento crítico sem utilização por período prolongado.',
    example: 'Equipamento crítico sem uso há 30 dias',
    severity: 'critical',
    default_audience: ['manager', 'director'],
    default_channels: ['app', 'email', 'whatsapp'],
    supports_escalation: true,
  }),
  defineNotificationEvent({
    slug: 'critical.overdue',
    module: 'equipamento',
    category: 'critical',
    label: 'Crítico vencido',
    description: 'Equipamento crítico com empréstimo vencido.',
    severity: 'critical',
    default_audience: ['manager', 'director'],
    default_channels: ['app', 'email', 'whatsapp'],
    supports_escalation: true,
  }),
  defineNotificationEvent({
    slug: 'critical.in_maintenance',
    module: 'equipamento',
    category: 'critical',
    label: 'Crítico em manutenção',
    description: 'Equipamento crítico indisponível por estar em manutenção.',
    severity: 'critical',
    default_audience: ['manager', 'director'],
    default_channels: ['app', 'email'],
    supports_escalation: true,
  }),
  defineNotificationEvent({
    slug: 'site.idle_equipment',
    module: 'equipamento',
    category: 'sites',
    label: 'Equipamentos ociosos na obra',
    description: 'Obra com equipamentos sem uso e custo associado.',
    example: 'Obra 650 — 3 equipamentos sem uso · R$ 4.050/mês',
    severity: 'warning',
    default_audience: ['manager'],
    default_channels: ['app', 'email'],
  }),
  defineNotificationEvent({
    slug: 'site.overdue_equipment',
    module: 'equipamento',
    category: 'sites',
    label: 'Muitos vencimentos na obra',
    description: 'Obra com volume elevado de equipamentos vencidos.',
    example: 'Obra possui 5 equipamentos vencidos',
    severity: 'critical',
    default_audience: ['manager'],
    default_channels: ['app', 'email', 'whatsapp'],
  }),
  defineNotificationEvent({
    slug: 'site.high_cost',
    module: 'equipamento',
    category: 'sites',
    label: 'Custo elevado na obra',
    description: 'Obra com custo mensal de equipamentos acima do esperado.',
    example: 'Custo mensal da obra R$ 42.000',
    severity: 'warning',
    default_audience: ['finance', 'manager'],
    default_channels: ['app', 'email'],
  }),
  defineNotificationEvent({
    slug: 'employee.equipment_overload',
    module: 'equipamento',
    category: 'employees',
    label: 'Excesso de equipamentos',
    description: 'Colaborador com quantidade de equipamentos acima da média da empresa.',
    example: 'João Silva — 12 equipamentos ativos',
    severity: 'warning',
    default_audience: ['manager'],
    default_channels: ['app'],
  }),
  defineNotificationEvent({
    slug: 'employee.long_possession',
    module: 'equipamento',
    category: 'employees',
    label: 'Maior tempo médio de posse',
    description: 'Colaborador com tempo médio de posse acima do padrão.',
    example: 'Maria Santos — média de posse 120 dias',
    severity: 'info',
    default_audience: ['manager'],
    default_channels: ['app'],
  }),
  defineNotificationEvent({
    slug: 'insight.return',
    module: 'equipamento',
    category: 'insight',
    label: 'Devolução sugerida',
    description: 'Recomendação de devolução para reduzir custo de ociosidade.',
    example: 'GERADOR 10 KVA — sem uso há 60 dias · economia R$ 2.200/mês',
    severity: 'info',
    default_audience: ['manager', 'finance'],
    default_channels: ['app', 'email'],
    supports_digest: true,
  }),
  defineNotificationEvent({
    slug: 'insight.reallocation',
    module: 'equipamento',
    category: 'insight',
    label: 'Realocação sugerida',
    description: 'Equipamento ocioso em uma obra com demanda em outra.',
    example: 'MARTELETE SDS PLUS ocioso na Obra 650 · demanda na Obra 720',
    severity: 'info',
    default_audience: ['manager'],
    default_channels: ['app', 'email'],
    supports_digest: true,
  }),
  defineNotificationEvent({
    slug: 'insight.replacement',
    module: 'equipamento',
    category: 'insight',
    label: 'Substituição sugerida',
    description: 'Equipamento com histórico que indica substituição.',
    example: '12 manutenções em 12 meses — considere substituição',
    severity: 'warning',
    default_audience: ['manager', 'finance'],
    default_channels: ['app', 'email'],
    supports_digest: true,
  }),
  defineNotificationEvent({
    slug: 'insight.cost_reduction',
    module: 'equipamento',
    category: 'insight',
    label: 'Redução de custo',
    description: 'Oportunidade agregada de economia no parque.',
    example: '3 equipamentos podem ser devolvidos · economia R$ 7.000/mês',
    severity: 'info',
    default_audience: ['finance', 'director'],
    default_channels: ['app', 'email'],
    supports_digest: true,
  }),
  defineNotificationEvent({
    slug: 'insight.anomaly',
    module: 'equipamento',
    category: 'insight',
    label: 'Comportamento atípico',
    description: 'Padrão de uso ou custo fora do esperado para o parque.',
    severity: 'warning',
    default_audience: ['manager', 'finance'],
    default_channels: ['app'],
    supports_digest: true,
  }),
  defineNotificationEvent({
    slug: 'digest.daily',
    module: 'equipamento',
    category: 'digest',
    label: 'Resumo diário',
    description: 'Consolidação diária dos principais indicadores e alertas.',
    example: '2 vencidos · 1 manutenção concluída · 3 parados · economia R$ 7.000/mês',
    severity: 'info',
    default_audience: ['director', 'manager', 'finance'],
    allowed_channels: ['email', 'whatsapp', 'app'],
    default_channels: ['email'],
    default_delivery: 'daily',
    supports_digest: true,
  }),
  defineNotificationEvent({
    slug: 'digest.weekly',
    module: 'equipamento',
    category: 'digest',
    label: 'Resumo semanal',
    description: 'Visão consolidada semanal para gestão executiva.',
    severity: 'info',
    default_audience: ['director', 'finance'],
    allowed_channels: ['email', 'whatsapp', 'app'],
    default_channels: ['email'],
    default_delivery: 'weekly',
    supports_digest: true,
  }),
];
